<?php
$url = "http://librarykaranjotkhatters.co.uk/api/books.php/";

$client = curl_init($url);
curl_setopt($client,CURLOPT_RETURNTRANSFER,true);
$response = curl_exec($client);

$results = json_decode($response);

?>

<h1>List of books</h1>

    <table id="books">
    <tr>
        <th>Book Id</th>
        <th>Name </th>
        <th>Link</th>
        <th>Content</th>
    </tr>

<?php foreach ($results as $result):?>
     <tr>
        <td><?php echo $result->id ?></td>
        <td><?php echo $result->name?></td>
        <td><?php echo $result->link ?></td>
        <td><?php echo $result->content ?></td>
     </tr>
<?php endforeach ?>
    </table>
