<?php
$url = "http://localhost/api/categories/";

$client = curl_init($url);
curl_setopt($client,CURLOPT_RETURNTRANSFER,true);
$response = curl_exec($client);

$results = json_decode($response);
$i = 0;
?>

<h1><List of books by categories</h1>

<?php foreach ($results as $result):?>
    <?php if ($result->category_id != $i):?>
        <h3><u></u><?php echo $result->category_name?></u></h3>

        <?php
        $i++;
        ?>
    <?php endif;?>
    <table id="books">
        <tr>
            <th>Book Id</th>
            <th>Name </th>
            <th>Link</th>
            <th>Content</th>
        </tr>

            <tr>
                <td><?php echo $result->book_id ?></td>
                <td><?php echo $result->book_name?></td>
                <td><?php echo $result->link ?></td>
                <td><?php echo $result->content ?></td>
            </tr>
    </table>

<?php endforeach ?>
